export const googleReviewsUrl =
  "https://www.google.com/maps/place/Asian+Foot+Spa/@40.1355242,-75.5411721,17z/data=!4m8!3m7!1s0x89c68f9dcd5af255:0x851b8e9be0f49fa1!8m2!3d40.1355242!4d-75.5411721!9m1!1b1";

export const googleWriteReviewUrl =
  "https://www.google.com/search?q=Asian+Foot+Spa+245+Schuylkill+Rd+Phoenixville#lrd=0x89c68f9dcd5af255:0x851b8e9be0f49fa1,3";

export type GoogleReview = {
  name: string;
  letter: string;
  color: string;
  meta: string;
  guide?: boolean;
  stars: number;
  when: string;
  label?: string;
  text?: string;
  more?: boolean;
  likes?: number;
  reply?: { when?: string; text: string };
};

export const barFills = [
  { stars: 5, width: "100%" },
  { stars: 4, width: "22%" },
  { stars: 3, width: "8%" },
  { stars: 2, width: "8%" },
  { stars: 1, width: "18%" },
];

export const googleReviews: GoogleReview[] = [
  {
    name: "Devi Tummala",
    letter: "D",
    color: "#5f7d95",
    meta: "9 reviews · 1 photo",
    stars: 1,
    when: "3 months ago",
    label: "Overpriced",
    text: "The first thing I noticed was the place was very warm. I asked if there was no AC. She said she just turned it on which was a lie. I was sweating the whole time . There was no technique to the massage, it was obvious the woman had no training. Will never go here again.",
    likes: 1,
  },
  {
    name: "Paulina",
    letter: "P",
    color: "#1a73e8",
    meta: "5 reviews · 10 photos",
    stars: 5,
    when: "8 months ago",
  },
  {
    name: "K Jain",
    letter: "K",
    color: "#188038",
    meta: "Local Guide · 14 reviews · 5 photos",
    guide: true,
    stars: 5,
    when: "8 months ago",
    label: "Reasonable price",
    text: "Nice massage",
    likes: 1,
  },
  {
    name: "Shubhada Menon",
    letter: "S",
    color: "#7b1fa2",
    meta: "Local Guide · 83 reviews · 25 photos",
    guide: true,
    stars: 5,
    when: "10 months ago",
    label: "Reasonable price",
    text: "Amy and May are great. My hubby discovered this place and now we both love it. They took care of all my aches n pains and I left feeling very relaxed after massage and it also included hot stones, hot towel n essential oils. Clean, neat and professional.",
    likes: 3,
  },
  {
    name: "Shirley Wolf",
    letter: "S",
    color: "#f57c00",
    meta: "6 reviews",
    stars: 5,
    when: "11 months ago",
    text: "Wonderful! I was so relaxed I didn't want to leave. Next time full massage along with the reflexology!",
    likes: 2,
  },
  {
    name: "Karthikeyan Subramaniam",
    letter: "K",
    color: "#e8710a",
    meta: "8 reviews",
    stars: 5,
    when: "a year ago",
    label: "Great price",
  },
  {
    name: "Raja Hayajneh",
    letter: "R",
    color: "#1967d2",
    meta: "Local Guide · 769 reviews · 322 photos",
    guide: true,
    stars: 5,
    when: "a year ago",
    text: "The BEST massage I have ever had! May is AWESOME",
  },
  {
    name: "Grace Yi",
    letter: "G",
    color: "#9334e6",
    meta: "Local Guide · 24 reviews · 1 photo",
    guide: true,
    stars: 5,
    when: "2 years ago",
    text: "I am very particular that I need",
    more: true,
  },
  {
    name: "anwar hyder",
    letter: "a",
    color: "#c5221f",
    meta: "Local Guide · 23 reviews · 1 photo",
    guide: true,
    stars: 1,
    when: "2 years ago",
    text: "I will never visit this place again.",
    more: true,
  },
  {
    name: "Michelle Tague",
    letter: "M",
    color: "#137333",
    meta: "11 reviews",
    stars: 4,
    when: "2 years ago",
    text: "Outstanding deep tissue and pressure point experience. Don't let the demure stature of these women fool you. Clean, comforting atmosphere. Made sure pressure was what I wanted. Very grateful I listened to my friends experience there and went. Husband and I are hooked.",
  },
  {
    name: "Maria Palumbo",
    letter: "M",
    color: "#8430ce",
    meta: "Local Guide · 98 reviews · 28 photos",
    guide: true,
    stars: 4,
    when: "2 years ago",
    text: "Excellent massage for being super affordable and convenient.",
  },
  {
    name: "Tati Carneiro",
    letter: "T",
    color: "#007b83",
    meta: "6 reviews",
    stars: 5,
    when: "2 years ago",
    text: "I need to talk . BEST massage therapist ever . OMG. If you are in doubt whether it is worth it or not. It's VERY worth it",
  },
  {
    name: "Guillermo Galvis",
    letter: "G",
    color: "#b06000",
    meta: "13 reviews · 1 photo",
    stars: 5,
    when: "2 years ago",
    text: "Very nice massage and very professional",
  },
  {
    name: "George D.",
    letter: "G",
    color: "#3c4043",
    meta: "Local Guide · 94 reviews · 44 photos",
    guide: true,
    stars: 4,
    when: "3 years ago",
    text: "Incredibly clean and relaxing environment, and amazing massage therapists. Will definitely be coming back!",
  },
  {
    name: "Jim Walker",
    letter: "J",
    color: "#174ea6",
    meta: "Local Guide · 52 reviews",
    guide: true,
    stars: 5,
    when: "3 years ago",
    text: "Great massage, peaceful spa music, clean, and friendly. Highly recommend",
  },
  {
    name: "steve",
    letter: "S",
    color: "#d32f2f",
    meta: "Local Guide · 78 reviews",
    guide: true,
    stars: 4,
    when: "3 years ago",
    text: "Massage was good. Cici was fairly strong. I will be back.",
  },
  {
    name: "Candice Kane",
    letter: "C",
    color: "#a142f4",
    meta: "11 reviews · 4 photos",
    stars: 5,
    when: "3 years ago",
    text: "I literally just left it was amazing Amy was great. Definitely coming back",
  },
  {
    name: "rjprieto7",
    letter: "r",
    color: "#e91e63",
    meta: "2 reviews",
    stars: 5,
    when: "3 years ago",
    text: "This Spa is not just feet! Received the most amazing full body professional massage here recently. Free hot stones at the end was a nice touch on a cold day. Left floating on a cloud of relaxation.",
  },
  {
    name: "Meghan Murray",
    letter: "M",
    color: "#e8710a",
    meta: "Local Guide · 13 reviews · 13 photos",
    guide: true,
    stars: 5,
    when: "4 years ago",
    text: "The prices are",
    more: true,
  },
  {
    name: "Giacomo Toscano",
    letter: "G",
    color: "#c62828",
    meta: "3 reviews",
    stars: 5,
    when: "4 years ago",
    text: "aches and pains.",
    more: true,
  },
  {
    name: "Michelle",
    letter: "M",
    color: "#d93025",
    meta: "Local Guide · 11 reviews · 1 photo",
    guide: true,
    stars: 5,
    when: "4 years ago",
    text: "Just left this place and had to leave a review. The reflexology is amazing, the massage is good too. I mostly enjoyed the scalp massage. They use hot stones, hot towel and oil. All essentials, I would say. I will be back next week!",
  },
  {
    name: "Parvaneh Z",
    letter: "P",
    color: "#757575",
    meta: "Local Guide · 30 reviews · 3 photos",
    guide: true,
    stars: 1,
    when: "4 years ago",
    text: "Not good at all .i used to go there , it was ok but last time i was there my massage was half way.it was deep tissue massage with hot stone but disappointing.will not go there any more .",
  },
  {
    name: "Yassin Jawad",
    letter: "Y",
    color: "#d32f2f",
    meta: "2 reviews",
    stars: 5,
    when: "4 years ago",
    text: "Best massage I've ever had Professional and good price",
  },
  {
    name: "Renee Prieto",
    letter: "R",
    color: "#c62828",
    meta: "1 review",
    stars: 5,
    when: "4 years ago",
    text: "I was very happy with my visit. The reception area is very clean, cute and relaxing, and staff is friendly. I received an amazing massage from Amy!",
  },
  {
    name: "Ayyada Paavam",
    letter: "A",
    color: "#0d652d",
    meta: "Local Guide · 10 reviews",
    guide: true,
    stars: 2,
    when: "Edited 4 years ago",
    text: "would prefer to",
    more: true,
  },
  {
    name: "Ting Zhang",
    letter: "T",
    color: "#1976d2",
    meta: "1 review",
    stars: 5,
    when: "4 years ago",
    text: "Me and my fiance went for a couples massage and it was so nice and relaxing! Felt Amazing!",
  },
  {
    name: "Troy Quinn Jr",
    letter: "T",
    color: "#388e3c",
    meta: "Local Guide · 159 reviews · 1,510 photos",
    guide: true,
    stars: 5,
    when: "5 years ago",
    text: "This is was my first time going to get a massage, thoroughly enjoyed it.",
    reply: {
      when: "5 years ago",
      text: "We are very happy to get your approval! Looking forward to your next visit!",
    },
  },
  {
    name: "ago usa",
    letter: "a",
    color: "#6d4c41",
    meta: "1 review · 1 photo",
    stars: 5,
    when: "5 years ago",
    text: "rejuvenating experience",
    more: true,
    reply: { text: "Thank you for coming. We will try our best to do better, thank you" },
  },
  {
    name: "Keith Yurev",
    letter: "K",
    color: "#174ea6",
    meta: "10 reviews",
    stars: 5,
    when: "5 years ago",
    text: "in a while.",
    more: true,
    reply: { text: "Thank you for your approval! Looking forward to seeing you again!" },
  },
  {
    name: "Alison Gontowski",
    letter: "A",
    color: "#c26401",
    meta: "Local Guide · 31 reviews · 20 photos",
    guide: true,
    stars: 5,
    when: "5 years ago",
    text: "One of the best massages I've ever had!!!",
    reply: { text: "We are very happy to get your approval! Looking forward to your next visit!" },
  },
];
