/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as EsIndexRouteImport } from './routes/es/index'
import { Route as EsFaqRouteImport } from './routes/es/faq'
import { Route as EsGalleryRouteImport } from './routes/es/gallery'
import { Route as EsPrivacyRouteImport } from './routes/es/privacy'
import { Route as EsReviewsRouteImport } from './routes/es/reviews'
import { Route as EsVisitRouteImport } from './routes/es/visit'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as LocationsSlugRouteImport } from './routes/locations/$slug'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as ZhIndexRouteImport } from './routes/zh/index'
import { Route as ZhFaqRouteImport } from './routes/zh/faq'
import { Route as ZhGalleryRouteImport } from './routes/zh/gallery'
import { Route as ZhPrivacyRouteImport } from './routes/zh/privacy'
import { Route as ZhReviewsRouteImport } from './routes/zh/reviews'
import { Route as ZhVisitRouteImport } from './routes/zh/visit'
import { Route as EsLocationsIndexRouteImport } from './routes/es/locations/index'
import { Route as EsLocationsSlugRouteImport } from './routes/es/locations/$slug'
import { Route as EsServicesIndexRouteImport } from './routes/es/services/index'
import { Route as EsServicesSlugRouteImport } from './routes/es/services/$slug'
import { Route as ZhLocationsIndexRouteImport } from './routes/zh/locations/index'
import { Route as ZhLocationsSlugRouteImport } from './routes/zh/locations/$slug'
import { Route as ZhServicesIndexRouteImport } from './routes/zh/services/index'
import { Route as ZhServicesSlugRouteImport } from './routes/zh/services/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const EsIndexRoute = EsIndexRouteImport.update({
  id: '/es/',
  path: '/es/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsFaqRoute = EsFaqRouteImport.update({
  id: '/es/faq',
  path: '/es/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EsGalleryRoute = EsGalleryRouteImport.update({
  id: '/es/gallery',
  path: '/es/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EsPrivacyRoute = EsPrivacyRouteImport.update({
  id: '/es/privacy',
  path: '/es/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EsReviewsRoute = EsReviewsRouteImport.update({
  id: '/es/reviews',
  path: '/es/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const EsVisitRoute = EsVisitRouteImport.update({
  id: '/es/visit',
  path: '/es/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/locations/$slug',
  path: '/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhIndexRoute = ZhIndexRouteImport.update({
  id: '/zh/',
  path: '/zh/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhFaqRoute = ZhFaqRouteImport.update({
  id: '/zh/faq',
  path: '/zh/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhGalleryRoute = ZhGalleryRouteImport.update({
  id: '/zh/gallery',
  path: '/zh/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhPrivacyRoute = ZhPrivacyRouteImport.update({
  id: '/zh/privacy',
  path: '/zh/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhReviewsRoute = ZhReviewsRouteImport.update({
  id: '/zh/reviews',
  path: '/zh/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhVisitRoute = ZhVisitRouteImport.update({
  id: '/zh/visit',
  path: '/zh/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const EsLocationsIndexRoute = EsLocationsIndexRouteImport.update({
  id: '/es/locations/',
  path: '/es/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsLocationsSlugRoute = EsLocationsSlugRouteImport.update({
  id: '/es/locations/$slug',
  path: '/es/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EsServicesIndexRoute = EsServicesIndexRouteImport.update({
  id: '/es/services/',
  path: '/es/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsServicesSlugRoute = EsServicesSlugRouteImport.update({
  id: '/es/services/$slug',
  path: '/es/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhLocationsIndexRoute = ZhLocationsIndexRouteImport.update({
  id: '/zh/locations/',
  path: '/zh/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhLocationsSlugRoute = ZhLocationsSlugRouteImport.update({
  id: '/zh/locations/$slug',
  path: '/zh/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhServicesIndexRoute = ZhServicesIndexRouteImport.update({
  id: '/zh/services/',
  path: '/zh/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhServicesSlugRoute = ZhServicesSlugRouteImport.update({
  id: '/zh/services/$slug',
  path: '/zh/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visit': typeof VisitRoute
  '/es/faq': typeof EsFaqRoute
  '/es/gallery': typeof EsGalleryRoute
  '/es/privacy': typeof EsPrivacyRoute
  '/es/reviews': typeof EsReviewsRoute
  '/es/visit': typeof EsVisitRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/zh/faq': typeof ZhFaqRoute
  '/zh/gallery': typeof ZhGalleryRoute
  '/zh/privacy': typeof ZhPrivacyRoute
  '/zh/reviews': typeof ZhReviewsRoute
  '/zh/visit': typeof ZhVisitRoute
  '/es/': typeof EsIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/zh/': typeof ZhIndexRoute
  '/es/locations/$slug': typeof EsLocationsSlugRoute
  '/es/services/$slug': typeof EsServicesSlugRoute
  '/zh/locations/$slug': typeof ZhLocationsSlugRoute
  '/zh/services/$slug': typeof ZhServicesSlugRoute
  '/es/locations/': typeof EsLocationsIndexRoute
  '/es/services/': typeof EsServicesIndexRoute
  '/zh/locations/': typeof ZhLocationsIndexRoute
  '/zh/services/': typeof ZhServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visit': typeof VisitRoute
  '/es/faq': typeof EsFaqRoute
  '/es/gallery': typeof EsGalleryRoute
  '/es/privacy': typeof EsPrivacyRoute
  '/es/reviews': typeof EsReviewsRoute
  '/es/visit': typeof EsVisitRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/zh/faq': typeof ZhFaqRoute
  '/zh/gallery': typeof ZhGalleryRoute
  '/zh/privacy': typeof ZhPrivacyRoute
  '/zh/reviews': typeof ZhReviewsRoute
  '/zh/visit': typeof ZhVisitRoute
  '/es': typeof EsIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/zh': typeof ZhIndexRoute
  '/es/locations/$slug': typeof EsLocationsSlugRoute
  '/es/services/$slug': typeof EsServicesSlugRoute
  '/zh/locations/$slug': typeof ZhLocationsSlugRoute
  '/zh/services/$slug': typeof ZhServicesSlugRoute
  '/es/locations': typeof EsLocationsIndexRoute
  '/es/services': typeof EsServicesIndexRoute
  '/zh/locations': typeof ZhLocationsIndexRoute
  '/zh/services': typeof ZhServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visit': typeof VisitRoute
  '/es/faq': typeof EsFaqRoute
  '/es/gallery': typeof EsGalleryRoute
  '/es/privacy': typeof EsPrivacyRoute
  '/es/reviews': typeof EsReviewsRoute
  '/es/visit': typeof EsVisitRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/zh/faq': typeof ZhFaqRoute
  '/zh/gallery': typeof ZhGalleryRoute
  '/zh/privacy': typeof ZhPrivacyRoute
  '/zh/reviews': typeof ZhReviewsRoute
  '/zh/visit': typeof ZhVisitRoute
  '/es/': typeof EsIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/zh/': typeof ZhIndexRoute
  '/es/locations/$slug': typeof EsLocationsSlugRoute
  '/es/services/$slug': typeof EsServicesSlugRoute
  '/zh/locations/$slug': typeof ZhLocationsSlugRoute
  '/zh/services/$slug': typeof ZhServicesSlugRoute
  '/es/locations/': typeof EsLocationsIndexRoute
  '/es/services/': typeof EsServicesIndexRoute
  '/zh/locations/': typeof ZhLocationsIndexRoute
  '/zh/services/': typeof ZhServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/gallery'
    | '/privacy'
    | '/reviews'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/visit'
    | '/es/faq'
    | '/es/gallery'
    | '/es/privacy'
    | '/es/reviews'
    | '/es/visit'
    | '/locations/$slug'
    | '/services/$slug'
    | '/zh/faq'
    | '/zh/gallery'
    | '/zh/privacy'
    | '/zh/reviews'
    | '/zh/visit'
    | '/es/'
    | '/locations/'
    | '/services/'
    | '/zh/'
    | '/es/locations/$slug'
    | '/es/services/$slug'
    | '/zh/locations/$slug'
    | '/zh/services/$slug'
    | '/es/locations/'
    | '/es/services/'
    | '/zh/locations/'
    | '/zh/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/gallery'
    | '/privacy'
    | '/reviews'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/visit'
    | '/es/faq'
    | '/es/gallery'
    | '/es/privacy'
    | '/es/reviews'
    | '/es/visit'
    | '/locations/$slug'
    | '/services/$slug'
    | '/zh/faq'
    | '/zh/gallery'
    | '/zh/privacy'
    | '/zh/reviews'
    | '/zh/visit'
    | '/es'
    | '/locations'
    | '/services'
    | '/zh'
    | '/es/locations/$slug'
    | '/es/services/$slug'
    | '/zh/locations/$slug'
    | '/zh/services/$slug'
    | '/es/locations'
    | '/es/services'
    | '/zh/locations'
    | '/zh/services'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/gallery'
    | '/privacy'
    | '/reviews'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/visit'
    | '/es/faq'
    | '/es/gallery'
    | '/es/privacy'
    | '/es/reviews'
    | '/es/visit'
    | '/locations/$slug'
    | '/services/$slug'
    | '/zh/faq'
    | '/zh/gallery'
    | '/zh/privacy'
    | '/zh/reviews'
    | '/zh/visit'
    | '/es/'
    | '/locations/'
    | '/services/'
    | '/zh/'
    | '/es/locations/$slug'
    | '/es/services/$slug'
    | '/zh/locations/$slug'
    | '/zh/services/$slug'
    | '/es/locations/'
    | '/es/services/'
    | '/zh/locations/'
    | '/zh/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  PrivacyRoute: typeof PrivacyRoute
  ReviewsRoute: typeof ReviewsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VisitRoute: typeof VisitRoute
  EsFaqRoute: typeof EsFaqRoute
  EsGalleryRoute: typeof EsGalleryRoute
  EsPrivacyRoute: typeof EsPrivacyRoute
  EsReviewsRoute: typeof EsReviewsRoute
  EsVisitRoute: typeof EsVisitRoute
  LocationsSlugRoute: typeof LocationsSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ZhFaqRoute: typeof ZhFaqRoute
  ZhGalleryRoute: typeof ZhGalleryRoute
  ZhPrivacyRoute: typeof ZhPrivacyRoute
  ZhReviewsRoute: typeof ZhReviewsRoute
  ZhVisitRoute: typeof ZhVisitRoute
  EsIndexRoute: typeof EsIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ZhIndexRoute: typeof ZhIndexRoute
  EsLocationsSlugRoute: typeof EsLocationsSlugRoute
  EsServicesSlugRoute: typeof EsServicesSlugRoute
  ZhLocationsSlugRoute: typeof ZhLocationsSlugRoute
  ZhServicesSlugRoute: typeof ZhServicesSlugRoute
  EsLocationsIndexRoute: typeof EsLocationsIndexRoute
  EsServicesIndexRoute: typeof EsServicesIndexRoute
  ZhLocationsIndexRoute: typeof ZhLocationsIndexRoute
  ZhServicesIndexRoute: typeof ZhServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/': {
      id: '/es/'
      path: '/es'
      fullPath: '/es/'
      preLoaderRoute: typeof EsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/faq': {
      id: '/es/faq'
      path: '/es/faq'
      fullPath: '/es/faq'
      preLoaderRoute: typeof EsFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/gallery': {
      id: '/es/gallery'
      path: '/es/gallery'
      fullPath: '/es/gallery'
      preLoaderRoute: typeof EsGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/privacy': {
      id: '/es/privacy'
      path: '/es/privacy'
      fullPath: '/es/privacy'
      preLoaderRoute: typeof EsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/reviews': {
      id: '/es/reviews'
      path: '/es/reviews'
      fullPath: '/es/reviews'
      preLoaderRoute: typeof EsReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/visit': {
      id: '/es/visit'
      path: '/es/visit'
      fullPath: '/es/visit'
      preLoaderRoute: typeof EsVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/': {
      id: '/zh/'
      path: '/zh'
      fullPath: '/zh/'
      preLoaderRoute: typeof ZhIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/faq': {
      id: '/zh/faq'
      path: '/zh/faq'
      fullPath: '/zh/faq'
      preLoaderRoute: typeof ZhFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/gallery': {
      id: '/zh/gallery'
      path: '/zh/gallery'
      fullPath: '/zh/gallery'
      preLoaderRoute: typeof ZhGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/privacy': {
      id: '/zh/privacy'
      path: '/zh/privacy'
      fullPath: '/zh/privacy'
      preLoaderRoute: typeof ZhPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/reviews': {
      id: '/zh/reviews'
      path: '/zh/reviews'
      fullPath: '/zh/reviews'
      preLoaderRoute: typeof ZhReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/visit': {
      id: '/zh/visit'
      path: '/zh/visit'
      fullPath: '/zh/visit'
      preLoaderRoute: typeof ZhVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/locations/': {
      id: '/es/locations/'
      path: '/es/locations'
      fullPath: '/es/locations/'
      preLoaderRoute: typeof EsLocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/locations/$slug': {
      id: '/es/locations/$slug'
      path: '/es/locations/$slug'
      fullPath: '/es/locations/$slug'
      preLoaderRoute: typeof EsLocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/services/': {
      id: '/es/services/'
      path: '/es/services'
      fullPath: '/es/services/'
      preLoaderRoute: typeof EsServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/services/$slug': {
      id: '/es/services/$slug'
      path: '/es/services/$slug'
      fullPath: '/es/services/$slug'
      preLoaderRoute: typeof EsServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/locations/': {
      id: '/zh/locations/'
      path: '/zh/locations'
      fullPath: '/zh/locations/'
      preLoaderRoute: typeof ZhLocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/locations/$slug': {
      id: '/zh/locations/$slug'
      path: '/zh/locations/$slug'
      fullPath: '/zh/locations/$slug'
      preLoaderRoute: typeof ZhLocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/services/': {
      id: '/zh/services/'
      path: '/zh/services'
      fullPath: '/zh/services/'
      preLoaderRoute: typeof ZhServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/services/$slug': {
      id: '/zh/services/$slug'
      path: '/zh/services/$slug'
      fullPath: '/zh/services/$slug'
      preLoaderRoute: typeof ZhServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  PrivacyRoute: PrivacyRoute,
  ReviewsRoute: ReviewsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VisitRoute: VisitRoute,
  EsFaqRoute: EsFaqRoute,
  EsGalleryRoute: EsGalleryRoute,
  EsPrivacyRoute: EsPrivacyRoute,
  EsReviewsRoute: EsReviewsRoute,
  EsVisitRoute: EsVisitRoute,
  LocationsSlugRoute: LocationsSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ZhFaqRoute: ZhFaqRoute,
  ZhGalleryRoute: ZhGalleryRoute,
  ZhPrivacyRoute: ZhPrivacyRoute,
  ZhReviewsRoute: ZhReviewsRoute,
  ZhVisitRoute: ZhVisitRoute,
  EsIndexRoute: EsIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ZhIndexRoute: ZhIndexRoute,
  EsLocationsSlugRoute: EsLocationsSlugRoute,
  EsServicesSlugRoute: EsServicesSlugRoute,
  ZhLocationsSlugRoute: ZhLocationsSlugRoute,
  ZhServicesSlugRoute: ZhServicesSlugRoute,
  EsLocationsIndexRoute: EsLocationsIndexRoute,
  EsServicesIndexRoute: EsServicesIndexRoute,
  ZhLocationsIndexRoute: ZhLocationsIndexRoute,
  ZhServicesIndexRoute: ZhServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
